# Generated by Django 4.2.1 on 2023-08-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product_details', models.TextField(blank=True, max_length=2000)),
                ('product_image', models.ImageField(blank=True, default=None, null=True, upload_to='product_image/')),
                ('offer_price', models.IntegerField(blank=True, null=True)),
                ('product_status', models.BooleanField(default=True)),
                ('product_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.brands')),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appauth.category')),
            ],
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_details', models.TextField(blank=True, max_length=2000)),
                ('variant_stock', models.PositiveBigIntegerField(default=0)),
                ('img1', models.ImageField(blank=True, default=None, null=True, upload_to='product_image/')),
                ('variant_status', models.BooleanField(default=True)),
                ('colour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.colour')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appauth.product')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
