# Generated by Django 4.2.1 on 2023-08-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
