# Generated by Django 4.2.1 on 2023-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0005_remove_userdetails_email_remove_userdetails_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
