# Generated by Django 4.2.1 on 2023-09-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0008_userdetails_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
