# Generated by Django 4.2.2 on 2023-08-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_note',
        ),
    ]
