# Generated by Django 4.2.1 on 2023-08-24 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0003_userdetails_delete_user_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0009_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Amount')], max_length=10)),
                ('discount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('applicable_type', models.CharField(choices=[('all', 'Category All'), ('category', 'Category')], max_length=10)),
                ('min_purchase', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appauth.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_applied', models.BooleanField(default=True)),
                ('coupon_applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.coupon')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
