# Generated by Django 4.2.1 on 2023-08-25 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appauth', '0004_alter_userdetails_user'),
        ('cart', '0010_coupon_usercoupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='appauth.userdetails'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='appauth.userdetails'),
        ),
    ]
