# Generated by Django 4.2.1 on 2023-08-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_orders_billing_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='cart.checkout'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='cart.checkout'),
        ),
    ]
