# Generated by Django 4.2.1 on 2023-08-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_orders_billing_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
