# Generated by Django 4.2.1 on 2023-09-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
