# Generated by Django 4.2.1 on 2023-09-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_remove_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_status',
            new_name='status',
        ),
    ]
