# Generated by Django 4.2.1 on 2023-09-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0018_rename_status_orders_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
