# Generated by Django 4.2.1 on 2023-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0022_orderedproducts_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_status',
        ),
        migrations.AlterField(
            model_name='orderedproducts',
            name='product_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Out for Shipping', 'Out for Shipping'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Returned', 'Returned')], default='Pending', max_length=20),
        ),
    ]
