# Generated by Django 4.2.1 on 2023-09-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0030_checkout_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='max_amount',
            new_name='min_amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='applicable_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='category',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='min_purchase',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='name',
        ),
    ]
