# Generated by Django 4.2.1 on 2023-09-14 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0032_alter_checkoutitem_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkoutitem',
            name='checkout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.checkout'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='billing_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_orders', to='cart.checkout'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shipping_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_orders', to='cart.checkout'),
        ),
    ]
