# Generated by Django 4.2.1 on 2023-09-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0033_alter_checkoutitem_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
