# Generated by Django 4.2.1 on 2023-09-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0034_cartitem_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_number',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
