# Generated by Django 4.2.1 on 2023-09-15 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0036_orders_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cartitem',
            new_name='order_cart_item',
        ),
    ]
