# Generated by Django 4.2.2 on 2023-09-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0037_rename_cartitem_orders_order_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
