# Generated by Django 4.2.2 on 2023-09-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0038_orderedproducts_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproducts',
            name='unit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
