# Generated by Django 4.2.2 on 2023-09-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0039_orderedproducts_unit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedproducts',
            name='unit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
